### PR TITLE
Update rust toolchain to 1.53.0

### PR DESCRIPTION
**Pull request by sruffell**
One of the libraries I would like to use needs the following feature from Rust 1.51.0:

https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#const-generics-mvp

### CODE REVIEW

**Comment by francis-starlab** [comment]
One minor concern here is will clippy still be happy after the update? I've noticed that on nightly clippy is unhappy.

**Comment by sruffell** [comment]
> One minor concern here is will clippy still be happy after the update? I've noticed that on nightly clippy is unhappy.

Hmm, you're correct. It looks like there are clippy errors when using the latest stable rust compiler.
I'll take a look and resubmit for review.

**Comment by francis-starlab** [comment]
@ALSchwalm this should be good now b/c the clippy errors in question where fixed as part of consolidated.

**Comment by francis-starlab** [comment]
@ALSchwalm this should be good now b/c the clippy errors in question where fixed as part of consolidated.

**Comment by francis-starlab** [comment]
Comandeering this branch to update to 1.56.1

**Pull request merged**
